language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "4.2"
  - "5.0"

# Use container-based Travis infrastructure.
sudo: false

branches:
  only:
    - master

before_install:
  # GUI for real browsers.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

  # Update to npm 3 (required due to npm2 postinstall bug)
  # https://github.com/FormidableLabs/builder/issues/30
  - npm install -g npm@3

script:
  - npm --version
  - node_modules/.bin/builder run check-ci

  # Prune deps to just production and ensure we can still build
  - npm prune --production
  - node_modules/.bin/builder run build
